<?php
$mem['running'][1][]=array(
	'积分商城',
	array(
		'module_config.php,1,points,模块设置',
		'points_cat.php,1,points,礼品分类',
		'points.php,1,points,礼品管理',
		'points_order.php,1,points,订单管理',
	)
);
?>